name: Update Visit & Like Data
on:
  repository_dispatch:
    types: [update_visit, update_like]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Update Data File
        id: update_data
        run: |
          DATA=$(cat data.json)
          VISIT_COUNT=$(echo $DATA | jq -r '.visitCount // 0')
          LIKE_COUNT=$(echo $DATA | jq -r '.likeCount // 0')
          if [ "${{ github.event.event_type }}" = "update_visit" ]; then
            NEW_VISIT=$((VISIT_COUNT + 1))
            NEW_LIKE=$LIKE_COUNT
          else
            NEW_VISIT=$VISIT_COUNT
            NEW_LIKE=$((LIKE_COUNT + 1))
          fi
          NEW_DATA=$(jq -n \
            --argjson visit $NEW_VISIT \
            --argjson like $NEW_LIKE \
            --arg time "$(date +'%Y-%m-%d %H:%M:%S')" \
            '{visitCount: $visit, likeCount: $like, lastUpdateTime: $time}')
          echo "$NEW_DATA" > data.json
          echo "new_visit=$NEW_VISIT" >> $GITHUB_OUTPUT
          echo "new_like=$NEW_LIKE" >> $GITHUB_OUTPUT

      - name: Add Update Log to Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueId = ${{ github.event.client_payload.issue_id }};
            const eventType = "${{ github.event.event_type }}";
            const newVisit = "${{ steps.update_data.outputs.new_visit }}";
            const newLike = "${{ steps.update_data.outputs.new_like }}";
            const updateTime = new Date().toLocaleString();
            const commentBody = `[${updateTime}] 数据更新：
            - 事件类型：${eventType === "update_visit" ? "访问计数" : "点赞计数"}
            - 当前访问数：${newVisit}
            - 当前点赞数：${newLike}`;
            await github.rest.issues.createComment({
              owner: "lopoph",
              repo: "666",
              issue_number: issueId,
              body: commentBody
            });

      - name: Commit & Push Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update: ${{ github.event.event_type }} (visit: ${{ steps.update_data.outputs.new_visit }}, like: ${{ steps.update_data.outputs.new_like }})"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          file_pattern: "data.json"
