name: 计数同步
on:
  push:
    paths:
      - "visit-signal.txt"
      - "like-signal.txt"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      
      - name: 统计计数并更新
        run: |
          VISIT=$(git log --oneline -- visit-signal.txt | wc -l)
          LIKE=$(git log --oneline -- like-signal.txt | wc -l)
          echo "{\"visitCount\":$VISIT,\"likeCount\":$LIKE}" > data.json
          git config --global user.name "actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "同步计数"
          git push origin main
