name: Sync Data From Issues
on:
  schedule:
    - cron: "*/1 * * * *" # 每1分钟同步一次
  issue_comment: # 收到评论时同步
    types: [created]

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Sync Visit & Like Count
        id: sync
        run: |
          # 获取Issues评论（统计点赞数）
          COMMENTS=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/lopoph/666/issues/${{ github.event.issue.number || 1 }}/comments")
          LIKE_COUNT=$(echo "$COMMENTS" | jq '[.[] | select(.body == "like")] | length')
          
          # 统计访问数（用Issues的浏览量）
          ISSUE=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/lopoph/666/issues/${{ github.event.issue.number || 1 }}")
          VISIT_COUNT=$(echo "$ISSUE" | jq '.views // 0')

          # 更新data.json
          NEW_DATA=$(jq -n \
            --argjson visit $VISIT_COUNT \
            --argjson like $LIKE_COUNT \
            --arg time "$(date +'%Y-%m-%d %H:%M:%S')" \
            '{visitCount: $visit, likeCount: $like, lastUpdateTime: $time}')
          echo "$NEW_DATA" > data.json

      - name: Commit Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Sync data: visit=${{ steps.sync.outputs.visit }}, like=${{ steps.sync.outputs.like }}"
          file_pattern: "data.json"
