name: Sync Data
on:
  schedule:
    - cron: "*/1 * * * *"
  issue_comment:
    types: [created]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count Data
        run: |
          # 1. 直接通过GitHub API统计点赞数（用grep匹配"like"评论）
          LIKE_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/lopoph/666/issues/1/comments" | grep -o '"body": "like"' | wc -l)
          
          # 2. 统计总评论数（用grep匹配评论对象）
          TOTAL_COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/lopoph/666/issues/1/comments" | grep -o '"id":' | wc -l)
          VISIT_COUNT=$((TOTAL_COMMENTS + 1))
          
          # 3. 直接写入data.json（无jq依赖）
          echo "{
            \"visitCount\": $VISIT_COUNT,
            \"likeCount\": $LIKE_COUNT,
            \"lastUpdateTime\": \"$(date +'%Y-%m-%d %H:%M:%S')\"
          }" > data.json

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update data: visit=$VISIT_COUNT, like=$LIKE_COUNT"
          file_pattern: "data.json"
