name: Sync Data From Issues
on:
  schedule:
    - cron: "*/1 * * * *"
  issue_comment:
    types: [created]

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Sync Visit & Like Count
        id: sync
        run: |
          # 1. 获取Issues评论（确保JSON格式）
          COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/lopoph/666/issues/${{ github.event.issue.number || 1 }}/comments")
          
          # 2. 验证JSON合法性
          if ! echo "$COMMENTS" | jq . > /dev/null 2>&1; then
            COMMENTS="[]"
          fi
          
          # 3. 统计点赞数
          LIKE_COUNT=$(echo "$COMMENTS" | jq '[.[] | select(.body == "like")] | length')
          
          # 4. 统计访问数
          TOTAL_COMMENTS=$(echo "$COMMENTS" | jq 'length')
          VISIT_COUNT=$((TOTAL_COMMENTS + 1))
          
          # 5. 生成data.json
          NEW_DATA=$(jq -n \
            --argjson visit "$VISIT_COUNT" \
            --argjson like "$LIKE_COUNT" \
            --arg time "$(date +'%Y-%m-%d %H:%M:%S')" \
            '{
              "visitCount": $visit,
              "likeCount": $like,
              "lastUpdateTime": $time
            }')
          
          echo "$NEW_DATA" > data.json

      - name: Commit Updated Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Sync data: visit=${{ steps.sync.outputs.visit }}, like=${{ steps.sync.outputs.like }}"
          file_pattern: "data.json"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
