name: 计数同步
on:
  push:
    paths:
      - "visit-signal.txt"
      - "like-signal.txt"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: 统计并写数据
        run: |
          # 直接统计文件的提交次数
          VISIT=$(git log --oneline -- visit-signal.txt | wc -l)
          LIKE=$(git log --oneline -- like-signal.txt | wc -l)
          echo "{\"visitCount\":$VISIT,\"likeCount\":$LIKE,\"time\":\"$(date)\"}" > data.json
          
          # 直接提交（跳过复杂的auto-commit）
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data.json
          git commit -m "同步计数：访问=$VISIT, 点赞=$LIKE"
          git push origin main --force-with-lease
