name: Sync Data From Issues
on:
  schedule:
    - cron: "*/1 * * * *"  # 每1分钟同步一次
  issue_comment:          # 收到评论时同步
    types: [created]

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Sync Visit & Like Count
        id: sync
        run: |
          # 1. 获取Issues的所有评论
          COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/lopoph/666/issues/${{ github.event.issue.number || 1 }}/comments")
          
          # 2. 统计点赞数（body为"like"的评论数量）
          LIKE_COUNT=$(echo "$COMMENTS" | jq '[.[] | select(.body == "like")] | length')
          
          # 3. 统计访问数（总评论数 + 1，1是初始访问）
          TOTAL_COMMENTS=$(echo "$COMMENTS" | jq 'length')
          VISIT_COUNT=$((TOTAL_COMMENTS + 1))
          
          # 4. 生成更新后的data.json
          NEW_DATA=$(jq -n \
            --argjson visit "$VISIT_COUNT" \
            --argjson like "$LIKE_COUNT" \
            --arg time "$(date +'%Y-%m-%d %H:%M:%S')" \
            '{
              "visitCount": $visit,
              "likeCount": $like,
              "lastUpdateTime": $time
            }')
          
          # 5. 写入data.json
          echo "$NEW_DATA" > data.json

      - name: Commit Updated Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Sync data: visit=${{ steps.sync.outputs.visit }}, like=${{ steps.sync.outputs.like }}"
          file_pattern: "data.json"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
